on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

name: Continuous integration

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-rs/cargo@v1
        with:
          command: build
